### PR TITLE
Custom landing partners

### PR DESCRIPTION
**Pull request by mojowen**
To be merged after #16 - adds support for customized landing pages for unions and some additional logos

### CODE REVIEW

**Review by nexussays — COMMENTED** [review]
Possibly just infer the custom landing from the presence of the logo ("customLandingLogo"?) but just a thought.

**Comment by nexussays** [comment]
I changed the base target to see the diff cleanly will change it back once the embed branch is in. Was going to rebase but the merge isn't that much more work and prevents messing with history so ignore prior comments on that.

**Comment by mojowen** [comment]
> Possibly just infer the custom landing from the presence of the logo ("customLandingLogo"?) but just a thought.

I don't think we want to offer this to every partner - just for folks that insist on it.

**Comment by mojowen** [comment]
I'll rename it `customLandingLogo` though - that's more descriptive

**Pull request merged**
