### PR TITLE
Copy updates for 2022

### PR DESCRIPTION
**Pull request by billylaing**
Howdy @mojowen! PtP had some copy updates. Can we merge this in to get it deployed?

Thanks!

### CODE REVIEW

**Comment by mojowen** [comment]
@billylaing sure - assuming you were able to get the form published and all that?

**Review by mojowen — DISMISSED** [review]

**Comment by billylaing** [comment]
@mojowen i didn't do the form publishing yet. I don't have access to the NPM repo. Are there some steps I need to do first?

**Comment by mojowen** [comment]
Hmm if the package updated isn’t published the site shouldn’t build - so
something is off there

**Comment by billylaing** [comment]
@mojowen ah, my bad. I didn't notice the form is a dependency. How can I get the form published?

**Comment by billylaing** [comment]
Here I am on NPM: https://www.npmjs.com/~billylaing

**Comment by mojowen** [comment]
@nexussays looks like I can’t add members to the org which would let me add @billylaing to the team to publish updates - would you mind transferring ownership to me and I can pass it off to the new folks?

https://www.npmjs.com/settings/ptp-us/members

**Comment by nexussays** [comment]
@mojowen done.

**Comment by billylaing** [comment]
~@mojowen does the post-submission jurisdiction display work in the netlify preview or did I break something?~

I see the CORS error now. Makes sense.

**Comment by billylaing** [comment]
@mojowen ok, I got over the hump getting the form updated and tested. this PR should be good to go now. Thanks!

**Review by mojowen — APPROVED** [review]

**Comment by billylaing** [comment]
Thamks @mojowen! I'll get this merged tomorrow.

**Comment by billylaing** [comment]
@mojowen actually I'll need someone with write access to do the merge. Can you help with that? Cheers.

**Comment by billylaing** [comment]
@mojowen can you get this merged? Wanted to get these copy changes out.

**Comment by mojowen** [comment]
@billylaing you should set up netlify to use the new org’s repo

**Comment by billylaing** [comment]
Thanks for the merge @mojowen. And yea, definitely going to be moving things over in the next couple weeks. We wanted to get this copy out before starting that process. I appreciate your help.

**Pull request merged**
